apiVersion: v1
kind: Service
metadata:
  name: insuretech-app-service
  labels:
    app: insuretech-app
spec:
  type: NodePort
  selector:
    app: insuretech-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
